# <center>EPIB 613 INTRODUCTION TO STATISTICAL SOFTWARE</center>

<center> McGill EBOH </center>

<center> Fall 2020 </center>

<center> Yi Lian </center>

# Lecture 3
1. Indexing
2. Import data
3. Exoprt data
4. Save and load workspace image

## 3.1 Indexing

The very basics for data management and manipulation
- Subsetting
- Sampling
- Sorting
- Merging
- Substitution
- ...

<b style="color:red;">Key Operators are "[ ]" and "$"</b>

<b style="color:red;">Can use integer, logical, character, factor, ...</b>

###### Recall object classes:
- Vector
- Matrix
- Array
- Data frame
- List
- (Factor)

### 3.1.1 Index a vector
##### Use integers

In [1]:
########## Lecture 3 ##########
vector <- c(6, 13, 20, 2, 0)
vector

[1]  6 13 20  2  0

In [2]:
# Pick the 2nd
vector[2]

[1] 13

In [3]:
# Pick 2nd - 4th
vector[2:4]

[1] 13 20  2

In [4]:
# Pick no. 1, 3, 5
vector[c(1, 3, 5)]

[1]  6 20  0

In [5]:
# Code like a pro
# This good practice makes it clearer for revisits and/or edits
# Reproducibility!

# Pick no. 1, 3, 5
index.integer <- c(1, 3, 5)
vector[index.integer]

[1]  6 20  0

In [6]:
# Re-order
vector[c(5,4,3,2,1)]

[1]  0  2 20 13  6

In [7]:
vector

[1]  6 13 20  2  0

In [8]:
order.index <- order(vector, decreasing = F)
order.index

[1] 5 4 1 2 3

In [9]:
vector[order.index]

[1]  0  2  6 13 20

In [10]:
# delete the 2nd and 4th - equivalent to keeping the rest
vector[-c(2,4)]

[1]  6 20  0

In [11]:
# change the value of the 5th
vector.new <- vector
vector.new[5] <- 1
vector.new

[1]  6 13 20  2  1

##### Use logicals
Generally used together with logical operators

In [12]:
# Note that the logical index has to have the same dimension as the object
index.logical <- c(T, F, T, F, T)
vector[index.logical]

[1]  6 20  0

In [13]:
# Usually we don't manually type T's and F's
vector[vector>4]

[1]  6 13 20

In [14]:
# How does it work?
vector>4

[1]  TRUE  TRUE  TRUE FALSE FALSE

###### Use characters

In [15]:
# Recall that we could give names to vector entries
names(vector) <- c("course level", "course code", "century", "decade", "year"); vector

course level  course code      century       decade         year 
           6           13           20            2            0

In [16]:
vector["century"]

century 
     20

In [17]:
index.character <- c("course level", "course code")
vector[index.character]

course level  course code 
           6           13

In [18]:
vector[rep("century", 3)]

century century century 
     20      20      20

### 3.1.2 Index a matrix

##### Now we have more than 1 dimensions. Use "," to separate dimensions.
- 1st dimension: row
- 2nd dimension: column
- 3rd ...

In [19]:
matrix <- matrix(c(3:14), nrow = 4, byrow = TRUE)
print(matrix)
# Note that the indices are given.

     [,1] [,2] [,3]
[1,]    3    4    5
[2,]    6    7    8
[3,]    9   10   11
[4,]   12   13   14


In [20]:
# The entry on the 2nd row 3rd column
matrix[2, 3]

[1] 8

In [21]:
# The 2nd row
matrix[2, ]

[1] 6 7 8

In [22]:
# The 1st and 3rd column
matrix[ , c(1, 3)]

[,1] [,2]
[1,]  3    5  
[2,]  6    8  
[3,]  9   11  
[4,] 12   14

In [23]:
# Change the order of columns. 
matrix[ , c(3, 1)]

[,1] [,2]
[1,]  5    3  
[2,]  8    6  
[3,] 11    9  
[4,] 14   12

##### Exercise

In [24]:
# Column 1 and 2, row 2 and 4
matrix[c(2,4), c(1,2)]

[,1] [,2]
[1,]  6    7  
[2,] 12   13

In [25]:
# Delete the 3rd row
matrix[-3, ]

[,1] [,2] [,3]
[1,]  3    4    5  
[2,]  6    7    8  
[3,] 12   13   14

Do you feel like using the logical indices for matrices?

###### Use the names

In [26]:
rownames(matrix)
colnames(matrix)

NULL

NULL

In [27]:
# Recall that we could give names to columns and rows

row.names <- c("row1", "row2", "row3", "row4")
col.names <- c("col1", "col2", "col3")
rownames(matrix) <- row.names
colnames(matrix) <- col.names
matrix

col1 col2 col3
row1  3    4    5  
row2  6    7    8  
row3  9   10   11  
row4 12   13   14

In [28]:
rownames(matrix)
colnames(matrix)

[1] "row1" "row2" "row3" "row4"

[1] "col1" "col2" "col3"

In [29]:
matrix(1:12, nrow = 4, dimnames = list(row.names, col.names))

col1 col2 col3
row1 1    5     9  
row2 2    6    10  
row3 3    7    11  
row4 4    8    12

In [30]:
matrix["row1", ]
# The output is a named vector as a result of dimension reduction

col1 col2 col3 
   3    4    5

In [31]:
matrix["row2", "col3"]

[1] 8

### 3.1.3 Index an array

In [32]:
array <- array(3:14, dim = c(2, 3, 2))
print(array)

, , 1

     [,1] [,2] [,3]
[1,]    3    5    7
[2,]    4    6    8

, , 2

     [,1] [,2] [,3]
[1,]    9   11   13
[2,]   10   12   14



In [33]:
array[ , , 1]

[,1] [,2] [,3]
[1,] 3    5    7   
[2,] 4    6    8

In [34]:
array[2, 3, 2]

[1] 14

In [35]:
array[1, , 2]

[1]  9 11 13

In [36]:
array[ , 1 , ]

[,1] [,2]
[1,] 3     9  
[2,] 4    10

### 3.1.4 Index a data frame

In [37]:
df <- data.frame(names = c("Lucy", "John", "Mark", "Candy"),
                 score = c(67, 56, 87, 91))

In [38]:
df

names score
1 Lucy  67   
2 John  56   
3 Mark  87   
4 Candy 91

In [39]:
df[2, ]
str(df[2, ])
# What is the structure of the result? Why?

names score
2 John  56

'data.frame':	1 obs. of  2 variables:
 $ names: Factor w/ 4 levels "Candy","John",..: 2
 $ score: num 56


In [40]:
df[ , 1]
# What is the structure of the result?

[1] Lucy  John  Mark  Candy
Levels: Candy John Lucy Mark

In [41]:
df[, 1, drop = F]
# What about now?

names
1 Lucy 
2 John 
3 Mark 
4 Candy

###### Use the names

In [42]:
# There are column (variable) names that are ready to be used in data frames.
names(df)

[1] "names" "score"

In [43]:
print(df[, "names"])

[1] Lucy  John  Mark  Candy
Levels: Candy John Lucy Mark


In [44]:
df$names
# data.frame$variable.name gives the variable.

[1] Lucy  John  Mark  Candy
Levels: Candy John Lucy Mark

In [45]:
# Usually the str() functions will give you an idea on how to access values in R objects
str(df)

'data.frame':	4 obs. of  2 variables:
 $ names: Factor w/ 4 levels "Candy","John",..: 3 2 4 1
 $ score: num  67 56 87 91


In [46]:
summary(df$score)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  56.00   64.25   77.00   75.25   88.00   91.00 

In [47]:
str(summary(df$score))

 'summaryDefault' Named num [1:6] 56 64.2 77 75.2 88 ...
 - attr(*, "names")= chr [1:6] "Min." "1st Qu." "Median" "Mean" ...


In [48]:
summary(df$score)[3]

Median 
    77 

In [49]:
attr(summary(df$score), "names")

[1] "Min."    "1st Qu." "Median"  "Mean"    "3rd Qu." "Max."

In [50]:
# What is John's score?
df[df$names == "John",]

names score
2 John  56

In [51]:
# How does this work?
df$names
df$names == "John"

[1] Lucy  John  Mark  Candy
Levels: Candy John Lucy Mark

[1] FALSE  TRUE FALSE FALSE

In [52]:
# Anyone scored 100?
print(df[df$score == 100,])

[1] names score
<0 rows> (or 0-length row.names)


In [53]:
# Highest score?
max(df$score)     # max() for maximum

[1] 91

In [54]:
# Who had the highes score?
df[df$score == max(df$score), ]

names score
4 Candy 91

In [55]:
# Note that this is still a data frame.
str(df[df$score == max(df$score), ])

'data.frame':	1 obs. of  2 variables:
 $ names: Factor w/ 4 levels "Candy","John",..: 1
 $ score: num 91


In [56]:
# I only need the name.
df[df$score == max(df$score), ]$names

[1] Candy
Levels: Candy John Lucy Mark

In [57]:
# Change the order of the columns
df[ , c("score", "names")]
# By now you should have realized that,
# we change the order of columns by picking the columns
# in the order that we want.

score names
1 67    Lucy 
2 56    John 
3 87    Mark 
4 91    Candy

### 3.1.5 Index a list

In [58]:
list <- list("Red", factor(c("a","b")), c(21,32,11), TRUE)
print(list)

[[1]]
[1] "Red"

[[2]]
[1] a b
Levels: a b

[[3]]
[1] 21 32 11

[[4]]
[1] TRUE



In [59]:
# single bracket gives the entire "sub-list"
# double bracket gives the R object stored in the "sub-list"
print(list[3])

[[1]]
[1] 21 32 11



In [60]:
list[3][[1]]

[1] 21 32 11

In [61]:
list[[3]]

[1] 21 32 11

In [62]:
str(print(list[3]))

[[1]]
[1] 21 32 11

List of 1
 $ : num [1:3] 21 32 11


In [63]:
str(print(list[[3]]))

[1] 21 32 11
 num [1:3] 21 32 11


In [64]:
list[[3]][2]

[1] 32

In [65]:
named.list <- list(course = "EPIB 613",
                   year = 2020,
                   pass.fail = T)
print(named.list)

$course
[1] "EPIB 613"

$year
[1] 2020

$pass.fail
[1] TRUE



In [66]:
str(named.list)

List of 3
 $ course   : chr "EPIB 613"
 $ year     : num 2020
 $ pass.fail: logi TRUE


In [67]:
named.list$year

[1] 2020

## 3.2 Import data
### 3.2.1 Use datasets that come with base R and R packages
Many R packages come with datasets that help explain how the packages and functions work, including those already installed when you download R and those already loaded everytime you open R.

In [68]:
head(mtcars) # You can use this dataset directly whenever you want.

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [69]:
# data() # Shows all datasets in base R.

Some require loading the package, e.g. "survival" package has a demo data "cancer".

In [70]:
# head(cancer)
# Load 'cancer' data before loading the 'survival' package will result in error.
library(survival)
head(cancer)

inst time status age sex ph.ecog ph.karno pat.karno meal.cal wt.loss
1  3    306 2      74  1   1        90      100       1175     NA     
2  3    455 2      68  1   0        90       90       1225     15     
3  3   1010 1      56  1   0        90       90         NA     15     
4  5    210 2      57  1   1        90       60       1150     11     
5  1    883 2      60  1   0       100       90         NA      0     
6 12   1022 1      74  1   1        50       80        513      0

### 3.2.2 Import from external sources
#### 1. Use Rstudio
        File -> Import Datasets
#### 2. Use code

## 3.3 Export data

In [71]:
df
# write.csv(df, file = "~/Desktop/df.csv")

names score
1 Lucy  67   
2 John  56   
3 Mark  87   
4 Candy 91

## 3.4 Save and load workspace image in R

- Two functions: <b>save( )</b> and <b>load( )</b> allows saving and loading R workspace image.

    - Saving workspace image will create a .RData file in your working directory.
    - Your current work is saved.
        - All the R objects in your environment
        - Exporting data in the previous section saves individual R objects

##### Exercise: modify an existing dataset for later use
- Load the fake data from the course github repo
    - https://raw.githubusercontent.com/ly129/EPIB613_2020/master/scores.csv
- Delete the curved score and pass fail status (columns), and delete the EPIB 607 records (rows)
- Change the names to "a", "b", "c", "d", "e" for privacy
- Randomly select 3 out of 5 students and discard the other 2
- Reorder the rows so that the scores are sorted in decreasing order
- Save the workspace image to a local location
- Save the data frame as a .csv file to a local location

In [72]:
exercise.l3 <- read.csv("https://raw.githubusercontent.com/ly129/EPIB613_2020/master/scores.csv")

exercise.l3 <- exercise.l3[exercise.l3$course == "epib607", c("students", "course", "scores")]

exercise.l3$students <- letters[1:5]

sample.index <- sample(1:5, size = 3, replace = F)

exercise.l3 <- exercise.l3[sample.index, ]

exercise.l3 <- exercise.l3[order(exercise.l3$scores, decreasing = T), ]

exercise.l3

# save.image("path/xxxx.RData")
# write.csv(exercise.l3, "path/xxxx.csv")

students course  scores
2 b        epib607 99    
5 e        epib607 84    
4 d        epib607 70