# <center>EPIB 613 INTRODUCTION TO STATISTICAL SOFTWARE</center>

<center> McGill EBOH </center>

<center> Fall 2020 </center>

<center> Yi Lian </center>

# Table of Contents<a id='toc'></a>

- [Lecture 1](#l1)
    1. Course walkthrouth
    2. R and Rstudio
    3. R markdown
- [Lecture 2](#l2)
    1. Basic computations in R
    2. How to create an object
    3. Data types
    4. Data strctures
    5. How to generate data
    6. Operators

# <a id='l1'></a> [Lecture 1](#toc)
## 1.1 Course walkthrough
### Logistics
- Location:
    - https://mcgill.zoom.us/j/98942683588?pwd=WnVBS0JkVmRCT0hCQlBJUjZBeXVmUT09

    - Meeting ID: 989 4268 3588

    - Passcode: 6132020
    
- Time: Fridays, 11:35-12:55
- Credits: 1
- Assignments: 3
- Contact: yi.lian@mail.mcgill.ca
- Office hours: by appointment

### Objectives
- R programming
- Hands-on data management and analysis
- Preparation for other courses

### Evaluations
- Pass/fail
    - Attend*
    - Participate*
    - Do your assignments
        - Submit via myCourses
        - __Must be in PDF format__
        - Code can be similar but written responses must be your own
        - Late assignments will be penalized by 10% per day
        
### Zoom lectures
- Please mute your microphone
- Please raise hand for questions and comments
- Lectures will be recorded and posted on myCourses
- A second device and/or a second screen is recommended
    - One for viewing the lecture and the other for running your code
    
### A few notes
- Be patient
    - with yourself, with R, with me
- Don't panic
    - I am always available
    - The [unofficial course TA](https://www.google.ca/) is always available
- Reproducibility
    - Annotate
    - Markdown

## 1.2 R and Rstudio
- R Console
    - It can do everything
    - Not very handy
    - Like most programming languages, people use an integrated development environment (IDE)
- Rstudio
    - The go-to IDE for R
    - A lot can be done through mouse-clicking
    - Cheatsheet https://github.com/rstudio/cheatsheets/raw/master/rstudio-ide.pdf

## 1.3 R Markdown
- A sample answer for your assignment
- Cheatsheet https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf

# <a id='l2'></a> [Lecture 2](#toc)
## 2.1 Basic computations in R

In [1]:
########## Lecture 2 ##########

In [2]:
2+5
2-5
2*5
2/5

[1] 7

[1] -3

[1] 10

[1] 0.4

In [3]:
2e3

[1] 2000

In [4]:
2^3; 8^(1/3)

[1] 8

[1] 2

In [5]:
sqrt(4)

[1] 2

In [6]:
log(4)    # Natural log

[1] 1.386294

In [7]:
exp(2)

[1] 7.389056

## 2.2 Create an R object
- Re-use the values by simply calling the the object
    - Reproducibility!
    - Avoid potential loss of precision
    - Avoid repeating expensive computation
- Can use variable names that make sense to yourself and to others
    - so that the others or the future you can better understand what you did

In [8]:
# Usually
x <- 5
x

[1] 5

In [9]:
y <- z <- 6
y
z

[1] 6

[1] 6

In [10]:
# <- , = and -> are equivalent when we assign values
instructor <- "Yi"
course = "EPIB 613"
"Fall 2020" -> semester

instructor; course; semester

[1] "Yi"

[1] "EPIB 613"

[1] "Fall 2020"

### Calculations with stored R objects

In [11]:
x + y

[1] 11

In [12]:
one.over.three <- 1/3
print(one.over.three)

[1] 0.3333333


In [13]:
one.over.three * 3

[1] 1

In [14]:
# If we copy-paste the result instead of saving it in an object
0.3333333 * 3
# loss of precision

[1] 0.9999999

### R is case sensitive.

In [15]:
course <- "EPIB 613"
Course <- "EPIB 601"
Course

[1] "EPIB 601"

### The old value will be replaced by the new one.

In [16]:
x

[1] 5

In [17]:
x <- y
x

[1] 6

###### Rule for creating an object:
- Variables can be alphabetic or alphanumeric, but not numeric (you are not allowed to create numeric variables).
- There are no restrictions to the length of the variable name.
- Avoid using the single letter names c, g, t, C, D, F, I and T as they are default names that are used by R. For instance, T and F are abbreviations for TRUE and FALSE in logical operations. We should avoid using names that are already used by the system.

## 2.3 Data types

In [18]:
number <- c(1, 2, 3)
class(number)

[1] "numeric"

In [19]:
# As in most programming languages, there are integers and floating-point numbers in R
class(5L)

[1] "integer"

In [20]:
# Double precision floating-point numbers in R
# is.double() checks whether an object is a double precision floating-point number
is.double(5); is.double(5L)

[1] TRUE

[1] FALSE

In [21]:
# How precise is double precision?
print(1/3)
options(digits = 22) # show more decimal points
print(1/3)
options(digits = 7) # reset to default

[1] 0.3333333
[1] 0.3333333333333333148296


In [22]:
letter <- letters[1:3]; letter
class(letter)

[1] "a" "b" "c"

[1] "character"

In [23]:
logical <- c(TRUE, FALSE)
class(logical)

[1] "logical"

In [24]:
factor <- as.factor(letters[1:3]); print(factor)
class(factor)

[1] a b c
Levels: a b c


[1] "factor"

In [25]:
mixed.factor <- factor(c(1,3,4,23423, "epib", "fall2020", T, F))
mixed.factor

[1] 1        3        4        23423    epib     fall2020 TRUE     FALSE   
Levels: 1 23423 3 4 epib fall2020 FALSE TRUE

## 2.4 Data structures
### 2.4.1* Scalar
Not considered as a stand-alone data structure because it is basically a vector of length 1.

In [26]:
x <- 5; x

[1] 5

### 2.4.2 Vector
In R, we work with vectors.

In [27]:
days.per.month <- c(31,28,31,30,31,30,31,31,30,31,30,31)
days.per.month

[1] 31 28 31 30 31 30 31 31 30 31 30 31

In [28]:
# We can add names to the vector for each entry
names(days.per.month) <- c('jan', 'feb', 'mar', 'apr', 
                           'may', 'jun', 'jul', 'aug',
                           'sep', 'oct', 'nov', 'dec')
print(days.per.month)

jan feb mar apr may jun jul aug sep oct nov dec 
 31  28  31  30  31  30  31  31  30  31  30  31 


In [29]:
# But the names will not affect calculations.
sum(days.per.month)

[1] 365

### 2.4.3 Matrix

In [30]:
mymatrix1 <- matrix(c(3:14), nrow = 4, byrow = TRUE)
print(mymatrix1)

     [,1] [,2] [,3]
[1,]    3    4    5
[2,]    6    7    8
[3,]    9   10   11
[4,]   12   13   14


In [31]:
mymatrix2 <- matrix(c(3:14), nrow = 4, byrow = FALSE)
print(mymatrix2)

     [,1] [,2] [,3]
[1,]    3    7   11
[2,]    4    8   12
[3,]    5    9   13
[4,]    6   10   14


In [32]:
rownames <- c("row1", "row2", "row3", "row4")
colnames <- c("col1", "col2", "col3")
rownames(mymatrix1) <- rownames
colnames(mymatrix1) <- colnames
print(mymatrix1)

     col1 col2 col3
row1    3    4    5
row2    6    7    8
row3    9   10   11
row4   12   13   14


### 2.4.4 Array

Scalars, vectors and matrices are basically all arrays of different dimensions
- Scalar: 1 x 1 array
- Vector of length k: 1 x k array
- Matrix of dimension m x n: m x n array

R treats these lower-dimensional ($\leq2$) arrays differently but they are essentially not very different. Python treats them in the same way.

Now let's look at a 3-dimensional array.

In [33]:
myarray <- array(1:24, dim = c(4,3,2))
print(myarray)

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24



##### A demonstration of high dimensional arrays - why is it useful?
Fake data:
- Drug: 1 = Exposed, 0 = Unexposed
- Cured: 1 = Yes, 0 = No
- BMI category: 1, 2, 3
- Age category: 1, 2, 3, 4

In [34]:
# Don't worry about the data generating process.
set.seed(6132020) # Make random numbers generated from sample() reproducible.

# A fake observation study
# Randomly assign ~60% of patients to take drug
drug <- sample(c(0,1), size = 100, replace = TRUE, prob = c(0.6, 0.4))

# Randomly assign ~20% of patients to be cured with or without taking the drug.
cured <- sample(c(0,1), size = 100, replace = TRUE, prob = c(0.2, 0.8))

# Some factors that may affect the efficacy of the drug
bmi.cat <- sample(1:3, size = 100, replace = TRUE) # Randomly assign BMI categories
age.cat <- sample(1:4, size = 100, replace = TRUE) # Randomly assign age categories

sex <- as.character(sample(c("female", "male"), size = 100, replace = TRUE))

data <- data.frame(drug, cured, bmi.cat, age.cat, sex) # Make our data frame
data$sex <- as.character(data$sex)
head(data, 10)

# The table below shows the first 10 rows of the fake dataset.
# This is a typical dataset you will see in Epidemiology.
# Each row is a patient, with their own information.
# Goal is to assess the drug effectiveness.

drug cured bmi.cat age.cat sex   
1  0    1     1       4       female
2  0    1     1       1       male  
3  1    1     3       2       male  
4  0    1     2       1       male  
5  0    1     2       3       male  
6  0    0     3       3       female
7  1    0     3       1       female
8  1    1     2       2       female
9  0    0     2       3       female
10 0    1     2       1       male

In [35]:
# By tabulating the data, we can assess the association (EPIB 601 material).
# If we only tabulate drug and outcome (cured or not), we get a 2x2 table
    ## which is a matrix or a 2-dimensional array.
# 1st dimension: drug, 2nd dimension: cured

data$drug <- factor(data$drug, levels = c(1,0))
data$cured <- factor(data$cured, levels = c(1,0))

table(data[c("drug", "cured")])

    cured
drug  1  0
   1 26  9
   0 52 13

In [36]:
# This may not be enough, we want to see how people with different BMI may differ.
    ## Confounder, also 601 material
# We now need a 2x2x3 table, which is a 3-dimensional array.
# 1st dimension: drug, 2nd dimension: cured, 3rd dimension: bmi.cat

table(data[c("drug", "cured", "bmi.cat")])

, , bmi.cat = 1

    cured
drug  1  0
   1  5  3
   0 17  3

, , bmi.cat = 2

    cured
drug  1  0
   1 12  4
   0 21  7

, , bmi.cat = 3

    cured
drug  1  0
   1  9  2
   0 14  3


In [37]:
# Further include age to see how age category comes into the association
# We now need a 2x2x3x4 table, which is a 4-dimensional array.
# 1st dimension: drug, 2nd dimension: cured, 3rd dimension: bmi.cat, 4th dimension: age.cat

# table(data)

### 2.4.5 Data frames
Data frame is the most commonly used data structure in R. Its columns can have different types. All elements of any column must have the same type, i.e. all numeric or all factor, or all character.

In [38]:
names <- c("Lucy", "John", "Mark", "Candy")
score <- c(67, 56, 87, 91)
pass <- c(T, F, T, T)
df <- data.frame(names, score, pass); print(df)

  names score  pass
1  Lucy    67  TRUE
2  John    56 FALSE
3  Mark    87  TRUE
4 Candy    91  TRUE


In [39]:
str(df) # checking the structure of an object

'data.frame':	4 obs. of  3 variables:
 $ names: Factor w/ 4 levels "Candy","John",..: 3 2 4 1
 $ score: num  67 56 87 91
 $ pass : logi  TRUE FALSE TRUE TRUE


### 2.4.6 List
In above data structures, data types and dimensions have to match. But not in lists.

In [40]:
mylist <- list("Red", factor(c("a","b")), matrix(c(21,32,11, 22,1,1), nrow = 3), TRUE)
print(mylist)

[[1]]
[1] "Red"

[[2]]
[1] a b
Levels: a b

[[3]]
     [,1] [,2]
[1,]   21   22
[2,]   32    1
[3,]   11    1

[[4]]
[1] TRUE



In [41]:
str(mylist)

List of 4
 $ : chr "Red"
 $ : Factor w/ 2 levels "a","b": 1 2
 $ : num [1:3, 1:2] 21 32 11 22 1 1
 $ : logi TRUE


### 2.4.7* Factors
In many online tutorials, factor is considered as a data structure - among vectors, matrices, etc.

In my opinion, factor is a data type.

Doesn't really matter.

In [42]:
ch.letter <- letters[1:3]
print(ch.letter)

[1] "a" "b" "c"


In [43]:
class(ch.letter)

[1] "character"

In [44]:
fac.letter <- as.factor(letters[1:3])
print(fac.letter)
# Note the additional 'Levels: a b c' in the output

[1] a b c
Levels: a b c


In [45]:
class(fac.letter)
# Should factor be considered as a data structure or a data type?

[1] "factor"

In [46]:
factor(1:10)

[1] 1  2  3  4  5  6  7  8  9  10
Levels: 1 2 3 4 5 6 7 8 9 10

## 2.5 How to generate data
##### Usually we start with vectors, by using the ombinations of the following
- c( )
- seq( )
- rep( )
- sequence( )

##### Then we can these vectors into higher dimensional data structures we just learned.

In [47]:
c(-1, 5.44, 100, 34123)

[1]    -1.00     5.44   100.00 34123.00

In [48]:
c(-1, "epib")

[1] "-1"   "epib"

In [49]:
-1:10 # Integers, by increments of 1.

[1] -1  0  1  2  3  4  5  6  7  8  9 10

In [50]:
(-1:10) * 0.1

[1] -0.1  0.0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.0

In [51]:
seq(from = 0.33, to = 9.33, by = 3)

[1] 0.33 3.33 6.33 9.33

In [52]:
seq(from = 0, to = 1, length = 5)

[1] 0.00 0.25 0.50 0.75 1.00

In [53]:
rep(1.2, times = 5)

[1] 1.2 1.2 1.2 1.2 1.2

In [54]:
rep(c("six", "one", "three"), times = 2)

[1] "six"   "one"   "three" "six"   "one"   "three"

In [55]:
rep(c("six", "one", "three"), each = 2)

[1] "six"   "six"   "one"   "one"   "three" "three"

In [56]:
sequence(5)

[1] 1 2 3 4 5

In [57]:
sequence(c(6, 1, 3))

[1] 1 2 3 4 5 6 1 1 2 3

In [58]:
# Can you make a numeric vector (-4, -3, -2, 0, 0.5, 1, 0, 0.5, 1, 1, 1, 2, 2, 3, 3)?

c(-4:-2, rep(seq(from = 0, to = 1, by = .5), times = 2), rep(c(1,2,3), each = 2))

[1] -4.0 -3.0 -2.0  0.0  0.5  1.0  0.0  0.5  1.0  1.0  1.0  2.0  2.0  3.0  3.0

In [59]:
(0:2) * 0.5

[1] 0.0 0.5 1.0

## 2.6 Operators
### 2.6.1 Arithmetic operators
###### Vector operations

In [60]:
a <- c(1, 8, 8)
b <- c(2, 8, 4)
a; b

[1] 1 8 8

[1] 2 8 4

In [61]:
a+1 # here 1 is considered as a vector (1, 1, 1)

[1] 2 9 9

In [62]:
a+b

[1]  3 16 12

In [63]:
a*b

[1]  2 64 32

In [64]:
a^2

[1]  1 64 64

##### Element-wise operations

###### Matrix operations
Also element-wise

In [65]:
c <- matrix(c(1,2,3,4), nrow = 2, byrow = T)
d <- matrix(c(5,6,7,8), nrow = 2, byrow = F)
print(c); print(d)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
     [,1] [,2]
[1,]    5    7
[2,]    6    8


In [66]:
c+1

[,1] [,2]
[1,] 2    3   
[2,] 4    5

In [67]:
c+d

[,1] [,2]
[1,] 6     9  
[2,] 9    12

In [68]:
c*d

[,1] [,2]
[1,]  5   14  
[2,] 18   32

In [69]:
c^2

[,1] [,2]
[1,] 1     4  
[2,] 9    16

##### Exercise
Try taking the sum of a matrix and a vector, what does R do?

In [70]:
a
sum(a)

[1] 1 8 8

[1] 17

In [71]:
c; rowSums(c)

[,1] [,2]
[1,] 1    2   
[2,] 3    4

[1] 3 7

##### (Optional) If you know linear algebra - cross product, dot product, etc.

In [72]:
a %*% b

[,1]
[1,] 98

In [73]:
a %o% b

[,1] [,2] [,3]
[1,]  2    8    4  
[2,] 16   64   32  
[3,] 16   64   32

In [74]:
c %*% d

[,1] [,2]
[1,] 17   23  
[2,] 39   53

### 2.6.2 Logical operators
Operators that return TRUE or FALSE

In [75]:
# Recall vector a and b from above.
print(a); print(b)

[1] 1 8 8
[1] 2 8 4


In [76]:
a == b # Equal or not?

[1] FALSE  TRUE FALSE

In [77]:
a != b # Not equal?

[1]  TRUE FALSE  TRUE

In [78]:
a > b

[1] FALSE FALSE  TRUE

In [79]:
a <= b

[1]  TRUE  TRUE FALSE

In [80]:
# And
a; b
a>5 & b>5

[1] 1 8 8

[1] 2 8 4

[1] FALSE  TRUE FALSE

In [81]:
# Or
a>=5 | b>=5

[1] FALSE  TRUE  TRUE

In [82]:
"ABC" == "ABC"

[1] TRUE

In [83]:
"ABC" == "abc"

[1] FALSE

In [84]:
TRUE + TRUE + FALSE # True = 1, False = 0.

[1] 2

In [85]:
random.numbers <- rnorm(10)* 100;
random.numbers

random.numbers > 10
# How many?
sum(random.numbers>10)

[1] 113.128431   1.888784 115.509304 -42.513736 104.502855   2.872818
 [7]   8.238992 182.472456 -94.490203  28.508501

[1]  TRUE FALSE  TRUE FALSE  TRUE FALSE FALSE  TRUE FALSE  TRUE

[1] 5

##### Exercise
1. There are 5 students - a, b, c, d, e
2. Their EPIB 607 scores are 80, 99, 55, 70, 84
3. Their EPIB 613 scores are 85, 90, 62, 40, 88
4. Scores are curved up by 10%
5. Passing grade is 65%
7. Assemble all of these information into a data frame, with columns indicating the course, score before curving, score after curving, pass/fail status. Each student will have two rows (one for each course).

In [86]:
students<- c('a','b','c','d','e')
scores.607 <- c(80, 99, 55, 70, 84)
scores.613 <-c(85, 90, 62, 40, 88)
Curved.607 <-scores.607 *1.1
Curved.613<-scores.613*1.1
Pass.607<-c(T,T,F,T,T)
Pass.613<-c(T,T,T,F,T)
Df<-data.frame(students, scores.607, scores.613, Curved.607, Curved.613, Pass.607, Pass.613)
Df

students scores.607 scores.613 Curved.607 Curved.613 Pass.607 Pass.613
1 a        80         85          88.0      93.5        TRUE     TRUE   
2 b        99         90         108.9      99.0        TRUE     TRUE   
3 c        55         62          60.5      68.2       FALSE     TRUE   
4 d        70         40          77.0      44.0        TRUE    FALSE   
5 e        84         88          92.4      96.8        TRUE     TRUE

In [88]:
students <- c(rep(letters[1:5], times = 2))
scores <-  c(80, 99, 55, 70, 84, 85, 90, 62, 40, 88)
course <- rep(c("epib607", "epib613"), each = 5)
curve <- scores*1.1
pass <- curve >= 65 
df <- data.frame(students, course, scores, curve, pass); df

students course  scores curve pass 
1  a        epib607 80      88.0  TRUE
2  b        epib607 99     108.9  TRUE
3  c        epib607 55      60.5 FALSE
4  d        epib607 70      77.0  TRUE
5  e        epib607 84      92.4  TRUE
6  a        epib613 85      93.5  TRUE
7  b        epib613 90      99.0  TRUE
8  c        epib613 62      68.2  TRUE
9  d        epib613 40      44.0 FALSE
10 e        epib613 88      96.8  TRUE